sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    name: "ESLint"
    script:
      - yarn lint
    name: "Unit tests"
    script:
      - yarn unit
    # name: "E2E tests"
    # script:
    #   - yarn installer:ci
    #   - yarn tests:e2e:ci
    name: "Build"
    script:
      - yarn build
