sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "8"
  - "10"

cache:
  yarn: true
  directories:
    - node_modules
    
install:
  - yarn
  
script: 
  - yarn lint
  # - yarn unit
  - yarn build

jobs:
  include:
    - stage: e2e
      if: branch IN (master, develop)
      script:
        - yarn installer:ci
        # - yarn tests:e2e:ci
