sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: "ESLint & Tests & Build"
    name: "ESLint"
    script: yarn lint
    - script: yarn unit
    name: "Unit tests"
    # - script:
    #   - yarn installer:ci
    #   - yarn tests:e2e:ci
    # name: "E2E tests"
    - script: yarn build
    name: "Build"
