language: node_js
node_js: '10'

cache:
  yarn: true
  directories:
    - packages/commercetools/api-client/node_modules
    - packages/commercetools/api-client/lib
    - packages/commercetools/helpers/node_modules
    - packages/commercetools/helpers/lib
    - packages/commercetools/composables/node_modules
    - packages/commercetools/composables/lib
    - packages/commercetools/theme/.nuxt
    - packages/commercetools/theme/node_modules

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

install:
  - yarn

jobs:
  include:
    - stage: Build
      name: Build
      script:
      - yarn build:ct

    - stage: test
      script: yarn test:ct:api-client
      name: Test commercetools api-client

    - stage: test
      script: yarn test:ct:composables
      name: Test commercetools composables

    - stage: test
      script: yarn test:ct:helpers
      name: Test commercetools helpers

    - build_image:
      name: "Build docker image"
      stage: docker_build
      script:
        - docker build -t registry.storefrontcloud.io/vsf-next-demo-storefrontcloud-io/vue-storefront:$COMMIT -f dev/docker/Dockerfile .
        - echo $DOCKER_PASSWORD | docker login  -u="$DOCKER_USERNAME" --password-stdin registry.storefrontcloud.io
        - docker push registry.storefrontcloud.io/vsf-next-demo-storefrontcloud-io/vue-storefront:$COMMIT

    - deploy_to_storefrontcloud:
      name: "Deploy to StorefrontCloud"
      stage: deploy
      script:
        - "curl -u $CLOUD_USERNAME:$CLOUD_PASSWORD -H 'Content-Type: application/json' -X POST -d \"{\\\"code\\\":\\\"vsf-next-demo\\\", \\\"frontContainerVersion\\\":\\\"$COMMIT\\\"}\" https://farmer.storefrontcloud.io/instances"

