sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "8"
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - lint
  - e2e
    
install:
  - yarn

jobs:
  include:
    - stage: lint
      script:
        - yarn lint
        # - yarn unit
        - yarn build
    - stage: e2e
      if: branch IN (master, develop)
      script:
        - yarn installer:ci
        # - yarn tests:e2e:ci
