version: '2.0'
services:
  app:
    # image: divante/vue-storefront:latest
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    env_file: docker/vue-storefront/default.env
    environment:
      VS_ENV: dev
    external_links:
      - vue-storefront-api_app_1:vue-storefront-api
      - vue-storefront-api_redis_1:redis
    networks:
      - default
      - vuestorefrontapi_default
    volumes:
      - '.babelrc:/var/www/.babelrc'
      - './config:/var/www/config'
      - './core:/var/www/core'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './.eslintignore:/var/www/.eslintignore'
      - './.eslintrc.js:/var/www/.eslintrc.js'
      - './lerna.json:/var/www/lerna.json'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './shims.d.ts:/var/www/shims.d.ts'
      - './package.json:/var/www/package.json'
      - './src:/var/www/src'
      - './var:/var/www/var'
    tmpfs:
      - /var/www/dist
    ports:
      - '3000:3000'
  nginx:
    image: nginx:alpine
    links:
      - app:vue-storefront
    external_links:
      - vue-storefront-api_app_1:vue-storefront-api
    networks:
      - default
      - vuestorefrontapi_default
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'

networks:
  vuestorefrontapi_default:
    external: true
