name: Deploy to Storefrontcloud
on:
  push:
    branches:
      - lc-pkg
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: https://registry.npmjs.org/
      - name: Build packages
        run: |
          yarn
          yarn build:core
          yarn build:ct
          yarn build:prismic
      - name: Publish canary version
        run: |
          yarn lerna publish --canary --yes --preid prealpha --dist-tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
